### ISSUE TITLE
can't use help in geany, misconfigured browser command

### ISSUE THREAD

**Issue by btreut** [flathub/org.geany.Geany#20] opened 2021-09-13 15:00 UTC
I am trying to use geany 1.37.1 installed from flathub, but when I try to get help, a popup appears that tells me that the browser command is misconfigured. 
![image](https://user-images.githubusercontent.com/8996291/133105459-18918d86-2afd-44f8-8c74-a93f4379ec15.png)
I tried several other commands, ie. firefox-bin (which is what I can see in the process list), flatpak run org.mozilla.firefox (which is how I succeeded to start firefox from the command line), but without success in getting help in geany. I also tried to adjust access rights for geany with flatseal, but did not succeed. Any suggestions what to enter as browser command and/or how to adjust the permissions?

I am using EndlessOS, a Debian derivate based on OSTree & Flatpak, see also my request for help at  the Endless [Community forum](https://community.endlessos.com/t/geany-cannot-display-help-missing-browser-command-firefox/17524).

PS: In the meantime I tried removing and reinstalling geany, but this does not change anything.

**Comment by wjt** [comment] 2021-09-13 20:11
What happens if you specify `xdg-open` as the browser command?

**Comment by btreut** [comment] 2021-09-14 13:48
thanks. It works like a charme with ```xdg-open```.

**Comment by wjt** [comment] 2021-09-14 17:56
I suggest reopening this because (a) it should work out of the box; (b) this line attempts to make it so:

https://github.com/flathub/org.geany.Geany/blob/9f57fdb3aa4fc09f532ed924739aace72990f223/org.geany.Geany.json#L66

**Comment by btreut** [comment] 2021-09-16 05:26
as @wjt suggested, I re-open the issue ...

**Comment by btreut** [comment] 2023-03-08 15:29
with the currently installed version 1.38, asking for help opens up the following dialog box, but I cannot choose any other browser than the default one, i.e. Chromium 
![image](https://user-images.githubusercontent.com/8996291/223755367-afc4ba17-1e5b-4c6d-8519-03bba1e40060.png)

**Comment by HugLifeTiZ** [comment] 2023-10-21 01:08
It seems like your xdg-desktop-portal might have been giving you fits at that time. I think I meant to say something like this back in March, but didn't for some reason. Is this still the case now?

I removed the section of my config file that specified a browser, and the sed segment might not even be necessary anymore, because the default is now "system default", and it works out of the box for me. We might be able to close this one up now.

**Comment by btreut** [comment] 2023-10-22 20:45
Sorry, I can't remember if this is still a problem. I'll try it again tomorrow.

**Comment by btreut** [comment] 2023-10-26 11:43
what is the expected behavior?

When I ask Geany 2.0 for help, I get every time the dialog box asking me for choosing a browser.

**Comment by HugLifeTiZ** [comment] 2023-10-26 13:13
That happens for me, too. I believe that is the expected behavior, and it's up to the desktop portal to give you an option to use an app every time or not. Plasma has a checkbox you can tick to use an app every time.

**Comment by HugLifeTiZ** [comment] 2023-12-15 14:05
I'm gonna go ahead and close this, because Geany now correctly defers to the portal to open help, and anything that feels bad with that is out of scope here. Thank you very much! 🙂

**Closed by HugLifeTiZ** 2023-12-15 14:05 UTC
